const UI_TEXT = {
  staticPage: {
    navHome: "Inicio",
    navSearch: "Buscar",
    libraryTitle: "Tu Biblioteca",
    newPlaylistPlaceholder: "Nueva playlist...",
    newPlaylistTitle: "Crear playlist",
    modalTitle: "Agregar canción",
    modalSongLabel: "Titulo",
    modalArtistLabel: "Artista",
    modalDurationLabel: "Duracion",
    modalOptional: "opcional",
    modalPositionLabel: "Posicion",
    modalSongPlaceholder: "Nombre de la cancion",
    modalArtistPlaceholder: "Nombre del artista",
    modalDurationPlaceholder: "3:30",
    modalPositionPlaceholder: "Al final",
    modalCancel: "Cancelar",
    modalAdd: "Agregar"
  },
  account: {
    defaultChip: "CU",
    settingsKicker: "Ajustes",
    profileTitle: "Tu perfil",
    nameLabel: "Nombre",
    themeLabel: "Tema",
    darkTheme: "Oscuro",
    lightTheme: "Claro",
    close: "Cerrar",
    saveChanges: "Guardar cambios",
    logout: "Salir del perfil",
    setupTitle: "Configura tu cuenta",
    setupCopy: "Escribe tu nombre y elige el tema de tu cuenta.",
    yourName: "Tu nombre",
    enter: "Entrar",
    nameRequired: "Debes escribir tu nombre.",
    saveNameRequired: "Escribe un nombre para guardar los cambios.",
    settingsSaved: "Ajustes guardados.",
    loggedOut: "Saliste del perfil."
  },
  search: {
    kicker: "Buscar",
    title: "Buscar en Melodify",
    copy: "Escribe un artista, cancion o estado de animo. Importaremos una playlist nueva dentro de Melodify.",
    termLabel: "Termino de busqueda",
    placeholder: "Por ejemplo: calm music, reggaeton, rock clasico",
    emptyQuery: "Escribe algo para buscar en Melodify.",
    requestError: "No se pudo consultar Melodify para esa busqueda.",
    homePlaceholder: "Que quieres reproducir?",
    showAll: "Mostrar todos",
    songsSection: "Canciones",
    recentSection: "Recientes",
    sourceSuffix: "Melodify"
  },
  addSong: {
    titleKicker: "Agregar cancion",
    title: "Buscar en Melodify",
    searchPlaceholder: "Buscar cancion o artista",
    searchButton: "Buscar",
    resultsTitle: "Resultados",
    recommendationsTitle: "Recomendaciones",
    recommendationsCopy: "Segun el genero o cantante de esta playlist",
    addButton: "Agregar",
    modalCopy: "Busca una cancion y agrega lo que quieras a la playlist actual. Tambien veras sugerencias parecidas por genero o cantante.",
    loadingSongs: "Buscando canciones en Melodify...",
    noMatchesPrefix: "No se encontraron coincidencias para",
    writeToSearch: "Escribe arriba para buscar una cancion o artista.",
    noRecommendations: "Sin recomendaciones disponibles.",
    loadingRecommendations: "Cargando recomendaciones...",
    noResultsYet: "No hay resultados todavia.",
    startTyping: "Empieza a escribir para buscar",
    selectPlaylistFirst: "Selecciona una playlist primero."
  },
  player: {
    djModeTitle: "Modo DJ",
    djEnabled: "Modo DJ activado.",
    djDisabled: "Modo DJ desactivado.",
    djStyleChangedPrefix: "DJ cambio el estilo a",
    djNoPlaylist: "DJ no encontro otra playlist para cambiar de estilo.",
    previewMissing: "Esta cancion no tiene preview disponible en Melodify.",
    previewError: "No se pudo reproducir el preview de esta cancion."
  },
  playlist: {
    favoritesName: "Mis favoritos",
    label: "PLAYLIST",
    featuredTitle: "Playlists destacadas",
    searchResultsTitle: "Resultados",
    titleColumn: "TITULO",
    emptyTitle: "Esta playlist esta vacia",
    emptyCopy: "Agrega canciones con el boton de arriba",
    addSong: "Agregar cancion",
    queueTitle: "Cola",
    nowPlayingTitle: "Sonando",
    noSongSelected: "No hay cancion seleccionada.",
    nextFromPrefix: "Siguiente de:",
    hideQueue: "Ocultar cola",
    showQueue: "Ver cola",
    previous: "Anterior",
    next: "Siguiente",
    queueEmpty: "La cola esta vacia.",
    queueEmptyWithHint: "La cola esta vacia. Agrega canciones para navegar con anterior y siguiente.",
    queueNoUpcoming: "No hay proximas canciones en la cola.",
    noDeleteFavorites: "No puedes eliminar la playlist Mis favoritos.",
    noDeleteOnlyOne: "No puedes eliminar la unica playlist.",
    writeName: "Escribe un nombre.",
    nameExists: "Ya existe una playlist con ese nombre.",
    actionFailed: "No se pudo completar la accion."
  },
  common: {
    close: "Cerrar",
    delete: "Eliminar",
    play: "Reproducir",
    playPreview: "Reproducir preview",
    nowPlayingNone: "Sin reproduccion",
    noMatchesPrefix: "No hay coincidencias para",
    noMatchesSuffix: "Mostrando canciones disponibles.",
    useSearchHint: "Usa Buscar para cargar playlists en Melodify.",
    searchNoSongs: "No se encontraron canciones.",
    noRecentContent: "Todavia no hay contenido reciente.",
    addToFavorites: "Agregar a favoritos",
    removeFromFavorites: "Quitar de favoritos",
    currentTag: "ACTUAL",
    byGenre: "Por genero",
    similarToCurrentSong: "Similares a esta cancion",
    songsWord: "canciones"
  },
  toast: {
    initialPlaylistsLoaded: "Playlists de Melodify cargadas.",
    initialPlaylistsError: "No se pudieron cargar las playlists iniciales de Melodify.",
    offlineFallbackLoaded: "Sin conexion: cargamos playlists locales para que uses la app al abrir index.html.",
    favoritesRemovedSuffix: "quitada de favoritos.",
    favoritesAddedSuffix: "agregada a favoritos.",
    trackAddedToPlaylistSuffix: "agregada a",
    trackRemovedSuffix: "eliminada.",
    playlistCreatedPrefix: "Playlist",
    playlistRemovedPrefix: "Playlist"
  }
} as const;

const uiFormat = {
  playlistMeta: (size: number): string => `Playlist · ${size} ${UI_TEXT.common.songsWord}`,
  searchResultsLoaded: (query: string): string => `Resultados cargados en Melodify: ${query}`,
  trackAddedToPlaylist: (trackTitle: string, playlistName: string): string => `"${trackTitle}" ${UI_TEXT.toast.trackAddedToPlaylistSuffix} ${playlistName}.`,
  favoriteRemoved: (trackTitle: string): string => `"${trackTitle}" ${UI_TEXT.toast.favoritesRemovedSuffix}`,
  favoriteAdded: (trackTitle: string): string => `"${trackTitle}" ${UI_TEXT.toast.favoritesAddedSuffix}`,
  djStyleChanged: (playlistName: string): string => `${UI_TEXT.player.djStyleChangedPrefix} ${playlistName}.`,
  playlistCreated: (name: string): string => `${UI_TEXT.toast.playlistCreatedPrefix} "${name}" creada.`,
  playlistRemoved: (name: string): string => `${UI_TEXT.toast.playlistRemovedPrefix} "${name}" eliminada.`,
  trackRemoved: (trackTitle: string): string => `"${trackTitle}" ${UI_TEXT.toast.trackRemovedSuffix}`,
  accountChipTitle: (name: string): string => `Perfil de ${name}`,
  searchSource: (artist: string): string => `${artist} · ${UI_TEXT.search.sourceSuffix}`,
  queuePreviousLabel: (): string => `${UI_TEXT.playlist.previous}`,
  noMatchesForQuery: (query: string): string => `${UI_TEXT.common.noMatchesPrefix} "${query}". ${UI_TEXT.common.noMatchesSuffix}`
};
